register:
  number: 1                                  # 注册的账号数量
  max_workers: 1                             # 多线程的最大工作线程数
  delete_low_balance_account: true           # 如果余额不足，重新注册账号
  delete_low_balance_account_threshold: 60   # 余额阈值，低于此值则重新注册
  email_server: 
    name: imap_email_server                  # 使用 IMAP 邮件服务器
    use_custom_address: true                 # 使用自定义邮箱地址
    custom_email_addresses:                  # 自定义邮箱配置
    - email: your_email@gmail.com            # 替换为你的真实邮箱
      imap_server: imap.gmail.com            # Gmail 的 IMAP 服务器
      imap_port: 993                         # IMAP 端口
      username: your_email@gmail.com         # 替换为你的真实邮箱
      password: your_app_password            # 替换为你的应用专用密码

  temp_email_server:                         # 临时邮箱配置（未使用）
    name: Gmailpm

  imap_email_server:                         # 默认 IMAP 配置（会被 custom_email_addresses 覆盖）
    imap_server: imap.gmail.com
    imap_port: 993
    username: your_email@gmail.com
    password: your_app_password

oneapi:
  enabled: false                             # 是否启用 OneAPI
  url: http://localhost:3000                 # OneAPI 服务器地址
  token: your_oneapi_token                   # OneAPI 令牌
  channel_url: http://localhost:3010         # 渠道 URL
  low_balance_threshold: 50                  # OneAPI 低余额阈值
